### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by zmb3** [tylerb/gotype-live#1]
This repository seems to be missing a license.

I was able to figure out that it's a fork and track down the original, but wanted to leave a friendly reminder here that the Go BSD license requires redistributions of source code to include a copy of the original license.

**Comment by AlekSi** [comment]
Also, without a license no-one can use this code: https://choosealicense.com/no-permission/. Yet VSCode depends on it.

**Comment by tylerstillwater** [comment]
Closed by https://github.com/tylerb/gotype-live/commit/440f9c77a467d5837d88978ce8494248140473be
